# Generated by Django 3.1.1 on 2020-09-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_auto_20200924_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=200, null=True)),
                ('projectTools', models.CharField(max_length=200, null=True)),
                ('projectDescription', models.TextField(null=True)),
                ('projectImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('myProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.myprofile')),
            ],
        ),
    ]
