# Generated by Django 3.1.1 on 2020-09-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='yearDuration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
